spring.datasource.url=jdbc:mysql://localhost:3306/servicebooking
spring.datasource.username=root
spring.datasource.password=Advance@1234

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.application.name=servicebooking

server.port=8081